### PR TITLE
Optimized even odd algorithm

### PR DESCRIPTION
**Pull request by sdshlanta**
Optimized even odd algorithm to take advantage of python numeric singleton behavior.  All numbers <256 are references to the same underlying objects.  So `is` wll be faster for the check as we only have to compare the pointers and not call to `__eq__`.

Let me know when you publish so I can publish my optimization!

### CODE REVIEW

**Comment by sdshlanta** [comment]
Using the following script you can see for yourself using this timing script (where `fast` and `slow` are the new version with `is` and the original), the new version is approximately 18% faster.


fast AVG time: 0.000010
fast TOT time: 9.821493
slow AVG time: 0.000011
slow TOT time: 11.491168


```import random
import timeit
import slow
import fast

def time_runs(func, data):
    times = []
    # prime loop for minimum overhead
    a = times.append
    start = 0
    end = 0
    for i in data:
        start = timeit.default_timer()
        func(i)
        end = timeit.default_timer()
        a(end - start)
    return times

# 32bit int generated by my ring fingers
random.seed(0b10100101011010101010101010101010)
data = [random.randint(1, 500) for _ in range(1000000)]

r1 = time_runs(fast.check_even_odd, data)
print('fast AVG time: %f' % (sum(r1)/len(r1)))
print('fast TOT time: %f' % (sum(r1)))
r2 = time_runs(slow.check_even_odd, data)
print('slow AVG time: %f' % (sum(r2)/len(r2)))
print('slow TOT time: %f' % (sum(r2)))
```

**Comment by sdshlanta** [comment]
Also, Navy > Chair Force #NRLthings #railgun <3

**Comment by sears-s** [comment]
bruh we can collab on my php dissertation for this

**Comment by sdshlanta** [comment]
> bruh we can collab on my php dissertation for this

Unfortunately I am a conscientious objector to PHP so this will not be possible, however if we were to do it in [vim](https://github.com/xoreaxeaxeax/vimmmex) or [powerpoint](https://www.youtube.com/watch?v=uNjxe8ShM-8) I would be interested.

**Pull request merged**
